import json
import codecs

stations = {
  "Ahmedabad Jn": "अहमदाबाद जं",
  "Surat": "सूरत",
  "Mumbai Central": "मुंबई सेंट्रल",
  "New Delhi": "नई दिल्ली",
  "Delhi": "दिल्ली",
  "Kolkata": "कोलकाता",
  "Chennai Central": "चेन्नई सेंट्रल",
  "Bangalore City Jn": "बेंगलुरु सिटी जं",
  "Hyderabad Decan": "हैदराबाद डेकन",
  "Pune Jn": "पुणे जं",
  "Jaipur": "जयपुर",
  "Lucknow": "लखनऊ",
  "Kanpur Central": "कानपुर सेंट्रल",
  "Varanasi Jn": "वाराणसी जं",
  "Patna Jn": "पटना जं",
  "Bhopal Jn": "भोपाल जं",
  "Indore Jn Bg": "इंदौर जं",
  "Nagpur": "नागपुर",
  "Agra Cantt": "आगरा कैंट",
  "Allahabad Jn": "प्रयागराज जं",
  "Bandra Terminus": "बांद्रा टर्मिनस",
  "Borivali": "बोरीवली",
  "Vapi": "वापी",
  "Vadodara Jn": "वडोदरा जं",
  "Surat - Mahuva": "सूरत - महुवा",
  "Palitana": "पालीताणा",
  "Jodhpur Jn": "जोधपुर जं",
  "Amritsar Jn": "अमृतसर जं",
  "Chandigarh": "चंडीगढ़",
  "Haridwar Jn": "हरिद्वार जं",
  "Dehradun": "देहरादून",
  "Jammu Tawi": "जम्मू तवी",
  "Kota Jn": "कोटा जं",
  "Ajmer Jn": "अजमेर जं",
  "Udaipur City": "उदयपुर सिटी",
  "Srinagar": "श्रीनगर",
  "Guwahati": "गुवाहाटी",
  "Dibrugarh": "डिब्रूगढ़",
  "Ranchi": "रांची",
  "Raipur Jn": "रायपुर जं",
  "Bilaspur Jn": "बिलासपुर जं",
  "Jabalpur": "जबलपुर",
  "Gwalior": "ग्वालियर",
  "Howrah Jn": "हावड़ा जं",
  "Sealdah": "सियालदह",
  "Visakhapatnam": "विशाखापत्तनम",
  "Vijayawada Jn": "विजयवाड़ा जं",
  "Tirupati": "तिरुपति",
  "Coimbatore Jn": "कोयंबटूर जं",
  "Madurai Jn": "मदुरई जं",
  "Ernakulam Jn": "एर्नाकुलम जं",
  "Thiruvananthapuram Central": "तिरुवनंतपुरम सेंट्रल",
  "Mangaluru Central": "मंगलुरु सेंट्रल",
  "Hubli Jn": "हुबली जं",
  "Mysuru Jn": "मैसूरु जं",
  "Shirdi": "शिर्डी",
  "Nashik Road": "नासिक रोड",
  "Aurangabad": "औरंगाबाद",
  "Solapur Jn": "सोलापुर जं",
  "Kolhapur": "कोल्हापुर",
  "Goa": "गोआ",
  "Madgaon Jn": "मडगांव जं",
  "Thiruvananthapuram": "तिरुवनंतपुरम",
  "Salem Jn": "सेलम जं",
  "Bengaluru": "बेंगलुरु",
  "Hazrat Nizamuddin": "हजरत निजामुद्दीन",
  "Anand Vihar Terminal": "आनंद विहार टर्मिनल",
  "Sarai Rohilla": "सराय रोहिल्ला",
  "Delhi Sarai Rohilla": "दिल्ली सराय रोहिल्ला",
  "Old Delhi": "पुरानी दिल्ली",
  "Delhi Cantt": "दिल्ली कैंट",
  "Rohtak Jn": "रोहतक जं",
  "Panipat Jn": "पानीपत जं",
  "Ambala Cantt Jn": "अंबाला कैंट जं",
  "Ludhiana Jn": "लुधियाना जं",
  "Jalandhar City": "जालंधर सिटी",
  "Mathura Jn": "मथुरा जं",
  "Bareilly Jn": "बरेली जं",
  "Moradabad Jn": "मुरादाबाद जं",
  "Meerut City": "मेरठ सिटी",
  "Faridabad": "फरीदाबाद",
  "Gurgaon": "गुरुग्राम",
  "Jorawarnagar Jn": "जोरावरनगर जं",
  "Gondal Jn": "गोंडल जं",
  "Rajkot Jn": "राजकोट जं",
  "Gandhidham Jn": "गांधीधाम जं",
  "Bhavnagar Terminus": "भावनगर टर्मिनस",
  "Jamnagar": "जामनगर",
  "Bharuch Jn": "भरूच जं",
  "Ankleshwar Jn": "अंकलेश्वर जं",
  "Bilimora Jn": "बिलिमोरा जं",
  "Navsari": "नवसारी",
  "Kim": "किम",
  "Udhna Jn": "उधना जं",
  "Kosad": "कोसड़",
  "Sachin": "साचिन",
  "Mangrol Road": "मांगरोल रोड",
  "Dholi": "ढोली",
  "Mota Varachha": "मोटा वराछा",
  "Amalsad": "अमलसाड",
  "Udvada": "उदवाडा",
  "Pardi": "पारडी",
  "Kolak": "कोलक",
  "Maroli": "मरोली",
  "Dungri": "डुंगरी",
  "Boisar": "बोईसर",
  "Vasai Road": "वसई रोड",
  "Nallasopara": "नालासोपारा",
  "Virar": "विरार",
  "Mira Road": "मीरा रोड",
  "Dahanu Road": "डहाणू रोड",
  "Palghar": "पालघर",
  "Hisar": "हिसार",
  "Bhagat Ki Kothi": "भगत की कोठी",
  "Palitana Weekly": "पालीताणा वीकली",
  "Sayaji Nagari": "सयाजी नगरी",
  "Mahuva": "माहुवा",
  "Rajkot": "राजकोट"
}

train_names_partial = {
  "Express": "एक्सप्रेस",
  "Superfast": "सुपरफास्ट",
  "SF Express": "SF एक्सप्रेस",
  "Mail": "मेल",
  "Rajdhani": "राजधानी",
  "Shatabdi": "शताब्दी",
  "Duronto": "दुरंतो",
  "Garib Rath": "गरीब रथ",
  "Jan Shatabdi": "जन शताब्दी",
  "Intercity": "इंटरसिटी",
  "Fast Passenger": "फास्ट पैसेंजर",
  "Passenger": "पैसेंजर",
  "Special": "स्पेशल",
  "Humsafar": "हमसफर",
  "Tejas": "तेजस",
  "Vande Bharat": "वन्दे भारत",
  "Amrit Bharat": "अमृत भारत",
  "Weekly": "वीकली"
}

output = {
  "stations": stations,
  "train_name_suffixes": train_names_partial
}

with codecs.open('src/utils/hi_dictionary.json', 'w', 'utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print("Dictionary written with", len(stations), "stations")
