import json, codecs

data = {
  "stations": {
    "Ahmedabad Jn": "अहमदाबाद जं",
    "Surat": "सूरत",
    "Mumbai Central": "मुंबई सेंट्रल",
    "New Delhi": "नई दिल्ली",
    "Delhi": "दिल्ली",
    "Kolkata": "कोलकाता",
    "Chennai Central": "चेन्नई सेंट्रल",
    "Bangalore City Jn": "बेंगलुरु सिटी जं",
    "Hyderabad Decan": "हैदराबाद डेकन",
    "Pune Jn": "पुणे जं",
    "Jaipur": "जयपुर",
    "Lucknow": "लखनऊ",
    "Kanpur Central": "कानपुर सेंट्रल",
    "Varanasi Jn": "वाराणसी जं",
    "Patna Jn": "पटना जं",
    "Bhopal Jn": "भोपाल जं",
    "Indore Jn Bg": "इंदौर जं",
    "Nagpur": "नागपुर",
    "Agra Cantt": "आगरा कैंट",
    "Allahabad Jn": "प्रयागराज जं",
    "Bandra Terminus": "बांद्रा टर्मिनस",
    "Borivali": "बोरीवली",
    "Vapi": "वापी",
    "Vadodara Jn": "वडोदरा जं",
    "Palitana": "पालीताणा",
    "Jodhpur Jn": "जोधपुर जं",
    "Amritsar Jn": "अमृतसर जं",
    "Chandigarh": "चंडीगढ़",
    "Haridwar Jn": "हरिद्वार जं",
    "Dehradun": "देहरादून",
    "Jammu Tawi": "जम्मू तवी",
    "Kota Jn": "कोटा जं",
    "Ajmer Jn": "अजमेर जं",
    "Udaipur City": "उदयपुर सिटी",
    "Guwahati": "गुवाहाटी",
    "Ranchi": "रांची",
    "Raipur Jn": "रायपुर जं",
    "Bilaspur Jn": "बिलासपुर जं",
    "Jabalpur": "जबलपुर",
    "Gwalior": "ग्वालियर",
    "Howrah Jn": "हावड़ा जं",
    "Sealdah": "सियालदह",
    "Visakhapatnam": "विशाखापत्तनम",
    "Vijayawada Jn": "विजयवाड़ा जं",
    "Tirupati": "तिरुपति",
    "Coimbatore Jn": "कोयंबटूर जं",
    "Madurai Jn": "मदुरई जं",
    "Ernakulam Jn": "एर्नाकुलम जं",
    "Thiruvananthapuram Central": "तिरुवनंतपुरम सेंट्रल",
    "Mangaluru Central": "मंगलुरु सेंट्रल",
    "Hubli Jn": "हुबली जं",
    "Mysuru Jn": "मैसूरु जं",
    "Nashik Road": "नासिक रोड",
    "Aurangabad": "औरंगाबाद",
    "Solapur Jn": "सोलापुर जं",
    "Kolhapur": "कोल्हापुर",
    "Madgaon Jn": "मडगांव जं",
    "Salem Jn": "सेलम जं",
    "Bengaluru": "बेंगलुरु",
    "Hazrat Nizamuddin": "हजरत निजामुद्दीन",
    "Anand Vihar Terminal": "आनंद विहार टर्मिनल",
    "Old Delhi": "पुरानी दिल्ली",
    "Rohtak Jn": "रोहतक जं",
    "Panipat Jn": "पानीपत जं",
    "Ambala Cantt Jn": "अंबाला कैंट जं",
    "Ludhiana Jn": "लुधियाना जं",
    "Jalandhar City": "जालंधर सिटी",
    "Mathura Jn": "मथुरा जं",
    "Bareilly Jn": "बरेली जं",
    "Moradabad Jn": "मुरादाबाद जं",
    "Jorawarnagar Jn": "जोरावरनगर जं",
    "Gondal Jn": "गोंडल जं",
    "Rajkot Jn": "राजकोट जं",
    "Gandhidham Jn": "गांधीधाम जं",
    "Bhavnagar Terminus": "भावनगर टर्मिनस",
    "Jamnagar": "जामनगर",
    "Bharuch Jn": "भरूच जं",
    "Ankleshwar Jn": "अंकलेश्वर जं",
    "Bilimora Jn": "बिलिमोरा जं",
    "Navsari": "नवसारी",
    "Udhna Jn": "उधना जं",
    "Amalsad": "अमलसाड़",
    "Udvada": "उदवाडा",
    "Pardi": "पारडी",
    "Boisar": "बोईसर",
    "Vasai Road": "वसई रोड",
    "Virar": "विरार",
    "Dahanu Road": "डहाणू रोड",
    "Palghar": "पालघर",
    "Hisar": "हिसार",
    "Bhagat Ki Kothi": "भगत की कोठी",
    "Mahuva": "माहुवा",
    "Rajkot": "राजकोट",
    "Surat - Mahuva": "सूरत - माहुवा",
    "Kutch": "कच्छ",
    "Sayaji Nagari": "सयाजी नगरी",
    "Dwarka": "द्वारका",
    "Okha": "ओखा",
    "Porbandar": "पोरबंदर",
    "Veraval": "वेरावल",
    "Somnath": "सोमनाथ",
    "Bhuj": "भुज",
    "Anand Jn": "आनंद जं",
    "Nadiad Jn": "नडियाद जं",
    "Mahesana Jn": "महेसाणा जं",
    "Mehsana Jn": "मेहसाणा जं",
    "Palanpur Jn": "पालनपुर जं",
    "Abu Road": "आबू रोड",
    "Sabarmati Jn": "साबरमती जं",
    "Gandhinagar Capital": "गांधीनगर कैपिटल",
    "Botad Jn": "बोटाद जं",
    "Surendranagar Jn": "सुरेंद्रनगर जं",
    "Dhrangadhra": "ध्रांगधरा",
    "Kalupur": "कालुपुर",
    "Khambhat": "खंभात",
    "Dabhoi Jn": "डभोई जं",
    "Godhra Jn": "गोधरा जं",
    "Dahod": "दाहोद",
    "Ratlam Jn": "रतलाम जं",
    "Ujjain Jn": "उज्जैन जं",
    "Manmad Jn": "मनमाड जं",
    "Jalgaon Jn": "जलगांव जं",
    "Bhusaval Jn": "भुसावल जं",
    "Akola Jn": "अकोला जं",
    "Wardha Jn": "वर्धा जं",
    "Gondia Jn": "गोंदिया जं",
    "Durg Jn": "दुर्ग जं",
    "Katni Jn": "कटनी जं",
    "Satna": "सतना",
    "Rewa": "रेवा",
    "Itarsi Jn": "इटारसी जं",
    "Khandwa": "खंडवा",
    "Nandurbar": "नंदुरबार",
    "Surat Mahuva": "सूरत माहुवा",
    "Palitana Weekly": "पालीताणा वीकली",
    "Hisar SF": "हिसार SF",
    "Sihor Gujarat": "सिहोर गुजरात",
    "Dhola Jn": "ढोला जं",
    "Botad": "बोटाद",
    "Sihor": "सिहोर",
    "Gujarat": "गुजरात"
  },
  "train_suffixes": {
    "Superfast Express": "सुपरफास्ट एक्सप्रेस",
    "SF Express": "SF एक्सप्रेस",
    "Weekly SF Express": "वीकली SF एक्सप्रेस",
    "Weekly Express": "वीकली एक्सप्रेस",
    "Jan Shatabdi Express": "जन शताब्दी एक्सप्रेस",
    "Shatabdi Express": "शताब्दी एक्सप्रेस",
    "Rajdhani Express": "राजधानी एक्सप्रेस",
    "Duronto Express": "दुरंतो एक्सप्रेस",
    "Garib Rath Express": "गरीब रथ एक्सप्रेस",
    "Humsafar Express": "हमसफर एक्सप्रेस",
    "Tejas Express": "तेजस एक्सप्रेस",
    "Vande Bharat Express": "वन्दे भारत एक्सप्रेस",
    "Amrit Bharat Express": "अमृत भारत एक्सप्रेस",
    "Intercity Express": "इंटरसिटी एक्सप्रेस",
    "Fast Passenger": "फास्ट पैसेंजर",
    "Passenger": "पैसेंजर",
    "Mail Express": "मेल एक्सप्रेस",
    "Special Express": "स्पेशल एक्सप्रेस",
    "Express Special": "एक्सप्रेस स्पेशल",
    "Express": "एक्सप्रेस",
    "Mail": "मेल",
    "Special": "स्पेशल",
    "Weekly": "वीकली",
    "Superfast": "सुपरफास्ट",
    "Terminus": "टर्मिनस",
    "Junction": "जंक्शन",
    "Central": "सेंट्रल",
    "Jn": "जं"
  }
}

with codecs.open('src/utils/hi_dictionary.json', 'w', 'utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Done:", len(data["stations"]), "stations")
